name: On Push
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    name: Test
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Setup Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
      - run: yarn install --frozen-lockfile
      - name: Install circom
        run: git clone https://github.com/iden3/circom.git
      - run: cd circom && git checkout v2.1.2
      - run: cd circom && cargo build --release
      - run: cd circom && cargo install --path circom
      - run: yarn compile-circuits
      - run: yarn generate-contract
      - run: yarn compile-contracts
      - run: cd package && yarn
      - run: cd package && yarn build
      - run: yarn test
